<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>QuantumCore.Game.Server</AssemblyName>
        <RootNamespace>QuantumCore.Game</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CsvCSharp" Version="1.0.3"/>
        <PackageReference Include="Enums.NET" Version="5.0.0"/>
        <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.11"/>
        <PackageReference Include="Microsoft.VisualStudio.Threading.Only" Version="18.7.23"/>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Game.Tests"/>
        <InternalsVisibleTo Include="Core.Tests"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Core\Core.csproj"/>
        <ProjectReference Include="..\..\Data\Game.Caching\Game.Caching.csproj"/>
        <ProjectReference Include="..\..\Data\Game.Persistence\Game.Persistence.csproj"/>
        <ProjectReference Include="..\..\Libraries\Game.Commands\Game.Commands.csproj"/>
    </ItemGroup>

</Project>
