// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using QuantumCore.Database;

namespace QuantumCore.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    internal class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("QuantumCore.Database.Account", b =>
            {
                b.Property<int>("AccountId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<string>("Password")
                    .HasColumnType("longtext CHARACTER SET utf8mb4");

                b.Property<string>("Username")
                    .HasColumnType("longtext CHARACTER SET utf8mb4");

                b.HasKey("AccountId");

                b.ToTable("Accounts");
            });
#pragma warning restore 612, 618
        }
    }
}