name: Bug Report
description: Report an issue or bug with the Quantum Core X.
title: "bug: "
labels: [ "type/bug" ]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help us diagnose and fix the issue. Before submitting a bug report, please check the [Reporting Bugs](https://github.com/MeikelLP/quantum-core-x/blob/main/CONTRIBUTING.md#reporting-bugs) section in the contributing guidelines.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what actually happened.
      placeholder: Describe the bug you encountered.
    validations:
      required: true

  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce?
      description: Steps to reproduce the behavior.
      placeholder: Steps to reproduce the behavior.

  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        > You can change the minimum log level to debug in the `appsettings.json` with `"Serilog:MinimumLevel:Default": "Debug"`

  - type: textarea
    id: stacktrace
    attributes:
      label: Stacktrace
      description: If applicable, paste the full stacktrace here.
      placeholder: Paste the full stacktrace here.

  - type: dropdown
    id: os-platform
    attributes:
      label: OS Platform
      description: Which OS platform are you using?
      options:
        - Windows
        - macOS
        - Linux
        - Other (please specify in the additional information)
    validations:
      required: true

  - type: textarea
    id: additional-info-and-notes
    attributes:
      label: Additional Information and Notes
      description: Add any other context about the problem here such as version of the interpreter, compiler, SDK, runtime environment, package manager, depending on what seems relevant.
      placeholder: Add any other context about the problem here.
    
