blank_issues_enabled: false
contact_links:
  - name: "Documentation"
    url: "https://meikellp.github.io/quantum-core-x/"
  - name: "Discord"
    url: "" # permanent invite link
  # todo: add more contact links