contact_links:
  - name: "Documentation"
    url: "https://meikellp.github.io/quantum-core-x/"
  - name: "Discord"
    url: "https://discord.gg/QAvu7Q9hmn" # permanent invite link
  # todo: add more contact links
