<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>835f39d8-1155-4ca8-b5a0-2406258ebe6d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Executables\Auth\Auth.csproj"/>
    <ProjectReference Include="..\Executables\Game\Game.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.4.6"/>
    <PackageReference Include="Aspire.Hosting.MySql" Version="13.4.6"/>
    <PackageReference Include="Aspire.Hosting.Valkey" Version="13.4.6"/>
  </ItemGroup>

</Project>
