<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <PackageReference Include="AwesomeAssertions" Version="9.6.0"/>
      <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0"/>
        <PackageReference Include="NSubstitute" Version="6.2.0"/>
      <PackageReference Include="Testcontainers.MySql" Version="4.14.0"/>
      <PackageReference Include="Testcontainers.PostgreSql" Version="4.14.0"/>
      <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
      <PackageReference Include="coverlet.collector" Version="10.0.1">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="xunit.v3" Version="4.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Libraries\Auth.Server\Auth.Server.csproj"/>
    </ItemGroup>

</Project>
