namespace QuantumCore.API.Packets;

public enum GamePacketsOut
{
    QuickBarAdd = 0x1C,
    QuickBarRemove = 0x1D,
    QuickBarSwap = 0x1E,
    ShopNoSpaceLeft = 0x26,
    ShopNotEnoughMoney = 0x26,
    ShopOpen = 0x26,
    Channel = 0x79,
    CharacterDead = 0x0e,
    CharacterDetails = 0x71,
    CharacterInfo = 0x88,
    CharacterMove = 0x03,
    CharacterPoints = 0x10,
    Characters = 0x20,
    CharacterUpdate = 0x13,
    Chat = 0x04,
    CreateCharacterFailure = 0x09,
    CreateCharacterSuccess = 0x08,
    DamageInfo = 0x87,
    DeleteCharacterFail = 0x0B,
    DeleteCharacterSuccess = 0x0A,
    Empire = 0x5a,
    GameTime = 0x6a,
    GroundItemAdd = 0x1A,
    GroundItemRemove = 0x1B,
    RemoveCharacter = 0x02,
    ServerStatusPacket = 0xD2,
    SetItem = 0x15,
    SetTarget = 0x3f,
    SpawnCharacter = 0x01,
    Warp = 0x41,
    Handshake = 0xff,
}